language: objective-c
osx_image: xcode7
xcode_workspace: samples/LookSample/LookSample.xcodeproj/project.xcworkspace
xcode_scheme: LookSample
xcode_sdk: iphonesimulator
before_install:
  - xcodebuild -version
  - sudo gem install xcpretty
script:
  - xcodebuild test -workspace samples/LookSample/LookSample.xcodeproj/project.xcworkspace -scheme LookSample -sdk iphonesimulator | xcpretty -c
notifications:
  email: false
