language: objective-c
osx_image: xcode7
xcode_workspace: samples/LookSample/LookSample.xcworkspace
xcode_scheme: LookSample
xcode_sdk: iphonesimulator
before_install:
  - xcodebuild -version
  - sudo gem install xcpretty
script:
  - make
notifications:
  email: false
